### ISSUE TITLE
Android NativeAd can't scroll when start touch on AdClickArea

### ISSUE THREAD

**Issue by zckrs** [floatinghotpot/cordova-plugin-flurry#23]
![screen-recording_20150414-123922](https://cloud.githubusercontent.com/assets/3020368/7135237/e4ec562e-e2a4-11e4-901d-92b55c91a351.gif)

**Comment by floatinghotpot** [comment]
The ad click area is a native view overlap the ad area in web view, only to accept user tap, driven by javascript code, it will follow the web content to scroll, but it won’t be scrollable itself.

**Comment by zckrs** [comment]
Any workarounds ? 

The user experience is weakened by this problem :-/

**Comment by floatinghotpot** [comment]
In the demo app, for demo purpose, all ad resources are displayed, which occupies very big area of screen.

In your app, you'd better display the ad in a smaller area, like a banner or something.

**Comment by floatinghotpot** [comment]
good news, it has been fixed in plugin v5.3.2.

**Comment by zckrs** [comment]
As possible I will try this =]

**Comment by floatinghotpot** [comment]
The two new issues mentioned has been fixed.

1. Scroll strange effect fixed by adjust touch location, code changes: 5453c84584dc03db3e29bb5f48cb54ca20e4f61b

2. Tracking view ghost area fixed by minimized to 1 pixel to avoid user touch. bb02bc90c72d172b1b1cea497159cf5ad327012c

I’ve tested, please update to plugin v5.3.4.
